USGS collection 2 into WOfS for DEAfrica
GeoscienceAustralia/wofs pull request #39
Opened 2021-05-13 03:57 UTC by eloise-b

Main changes:
Edits to `filters.py`
- adding a C2 filter/mask, to do the cloud and cloud shadow masking
- uses the `pixel_quality` layer and from that layer `dilated_cloud` and `cloud_shadow`  
Edits to `virtual_product.py`
- if C2 scaling is used, also use the `woffles_c2`
Edits to `wofls.py`
- adding `woffles_c2` which uses `filter_c2`

2021-05-13 03:59 UTC, eloise-b commented
@fangfy @omad @alexgleith

2021-05-17 22:27 UTC, alexgleith requested changes
Some comments throughout.

One thing that I think you should change is to use less commits, so be deliberate about them.

I think this is a good tutorial on how to do that: https://dev.to/aman_singh/how-to-cleanup-commit-history-using-git-reset-46p3

2021-05-17 22:27 UTC, alexgleith commented on wofs/filters.py
> +    #masking[((pq & C2_DILATED_BITS) | (pq & C2_CIRRUS_BITS)).astype(np.bool)] += constants.MASKED_CLOUD
Why are these all still there?

2021-05-17 22:27 UTC, alexgleith commented on wofs/filters.py
> +#C2_CLOUD_BITS = #0x000C # 1100 2nd and 3rd bit #try doing them as 2 checks instead of one
Commented?

2021-05-17 22:27 UTC, alexgleith commented on wofs/virtualproduct.py
> +from wofs.wofls import woffles_ard, woffles_c2
I wonder if we should name it `woffles_usgs_c2` to be more specific.

2021-05-17 22:27 UTC, alexgleith commented on wofs/virtualproduct.py
> +                      scale_factor=0.275, add_offset=-2000, clip_range=(0, 10000))
Might be nice to have a comment that references where we can check these values.

2021-05-17 22:27 UTC, alexgleith commented on wofs/wofls.py
> +        #| pq_filter(ard.pixel_quality)
Another comment to remove

2021-05-18 02:47 UTC, eloise-b commented
@alexgleith I tried to clean up the commits, not sure what happened with it though! I also tidied up the parts that were commented out and updated `woffles_c2` to e `woffles_usgs_c2`

2021-05-18 02:59 UTC, alexgleith commented
What I suggest you do is something like:

```
git reset --soft fe4dd7c197d7bfe2641545959249071b9340b3d2
```

Then do a new commit, so:

```
git commit -am "a nice message goes here"
```

And then push the results, either to a new branch (safe) or to this branch (`git push --force`, which is a little dangerous).

2021-05-24 03:39 UTC, alexgleith approved these changes

2021-05-24 03:40 UTC, merged